### ISSUE TITLE
[몬스터] 특정 지형에서 스스로 판단해서 움직이고 플레이어를 감지해 공격하는 적

### ISSUE THREAD

**Issue by eric1306** [KUnity2023/unity-dusk-mobile#21]
1. 바닥의 끝을 감지해 방향 전환
2. 플레이어 감지를 통한 추적
3. 플레이어 공격

**Comment by eric1306** [comment]
플레이어와의 Collision 처리를 위한 OnTrigger 함수 내부에 반드시 작성

**Comment by 3daysJin** [comment]
기본적인 사항들은 구현 되었으나 코드는 개판 5분전,
피직스2d 설정했음에도 불구하고 플레이어 레이어와 왜 물리적 충돌이 일어나는지 도대체 해결을 못함
더 화나는건 enemy 끼리 충돌 해제 해놓은건 잘만 적용됨
