### ISSUE TITLE
[버그] 연속 점프가 되는 오류

### ISSUE THREAD

**Issue by eric1306** [KUnity2023/unity-dusk-mobile#30]
Stage1_1 PAssableFloor가 3개 연속으로 있는 왼쪽 지형에서 점프키 연타시 2단으로 점프가 되는 현상이 있음.

**Comment by 3daysJin** [comment]
해당 사항 점검 결과 캐릭터 아래에 위치한 지면 감지 센서 근처에 passableFloor이 있어서 idle 상태 전환 전에 재차 점프가 가능한것으로 보임

그런데 머리나 몸통이 겹쳐있을때 점프가 되지는 않음 

재차 밟고 점프하는 것 처럼 의도된 사항은 맞음

애니메이션을 개선할 여지는 존재 O
@eric1306

**Comment by eric1306** [comment]
의도한 사항이라면 여기서 닫겠습니다! 수고하셨습니다
