### ISSUE TITLE
[에셋] BringOfDeath Pivot 위치때문에 Flip 이상하게 되는 문제 해결방법

### ISSUE THREAD

**Issue by eric1306** [KUnity2023/unity-dusk-mobile#31]
Bring of death->sprite sheet -> 스프라이트 이미지 누르기 ->

![1](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/77cfd1f2-94bf-4b65-8411-dd14bd22c373)

 Sprite Editor 클릭 ->

![2](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/45522037-0db9-48e8-80a6-1467cf6309e2)

박스 누르고 가운데 똥글뱅이를 몬스터의 중앙으로 이동 ->

![3](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/693f1b85-82d0-4269-bf40-d43a1a6a6445)

우상단 apply 누르고 닫기 ->테스트 해보면 flip이 해당 부분을 기준점으로 잘 되는걸 확인 가능합니다.

![4](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/f04fa126-a857-41cc-a155-90026ce8096c)

장점: 드드드득거리는거 해결가능
단점: 일일히 다 수정해야함.

**Comment by 3daysJin** [comment]
좋은 방법이네요~
적용은
