### ISSUE TITLE
[버그?] NullReference Exception

### ISSUE THREAD

**Issue by eric1306** [KUnity2023/unity-dusk-mobile#36]
Enemy에서 나네요. 확인 부탁드립니다.

![스크린샷 2023-12-02 113753](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/4b579088-ab94-479f-9abd-0d2ec7b253e6)

**Comment by 3daysJin** [comment]
해당 스크립트 내에서 해당 함수 지워버려도 상관없습니다. 디버깅용이라 오류가 나는 이유는 몰루지만 없애도 상관없는 함수입니다.
