### ISSUE TITLE
[수정] 캐릭터에 조이스틱 자동 할당

### ISSUE THREAD

**Issue by eric1306** [KUnity2023/unity-dusk-mobile#37]
현재 게임 Flow

![스크린샷 2023-12-02 173645](https://github.com/KUnity2023/unity-dusk-mobile/assets/64396933/81ea0d5e-349f-4950-9337-7b4d10307cdd)

게임 구조는 Selected 된 Character Prefab이 PlayerSpawn GameObject의 Transform에 스폰되는 구조임. 다만 현재의 구조에서는 이게 불가능. TEST를 위해 캐릭터를 하나 배치하고 연결까지 했기 때문. 

따라서 CharacterManager 의 Awake or Start에서 해당 scene의 JoyStick을 찾아서 넣는 코드 작업이 요구됨. 부탁

**Comment by 3daysJin** [comment]
CharacterManager 의 Awake or Start에서 해당 scene의 JoyStick을 찾아서 넣는
 -> GameObject.Find("Joystick").GetComponent<bl_Joystick>();

조이스틱의 게임 오브젝트 이름은 항상 Joystick을 사용해야함
@eric1306

**Comment by eric1306** [comment]
메인에서 풀 받는 CharacterManager 스크립트에 해당 코드가 없는데 제가 직접 추가해야하는건가요? 확인 한번 부탁드립니다. 추가해야하는거면 제가 추가해놓겠습니다. @3daysJin

**Comment by 3daysJin** [comment]
#50 해당 PR 통해서 머지된 버전 main에 반영 되었습니다~ @eric1306

**Comment by eric1306** [comment]
굿
