### ISSUE TITLE
Passable Floor 오동작 해결 및 구현 방법, 개선 요구사항

### ISSUE THREAD

**Issue by 3daysJin** [KUnity2023/unity-dusk-mobile#44]
1. 플레이어 캐릭터에 passable Floor 스크립트 추가
2. passble Floor 스크립트에 본인 2d box 콜라이더 등록
3. Tile의 PassableFloor는 PassablePlatform 태그, Platform 레이어 등록

[필요 개선사항, To do]
1. 스스로 본인 콜라이더 초기화해서 들고오도록
2. 플레이어 캐릭터 프리팹에 해당 스크립트 추가되어 있도록 반영
3. 모바일 조작에 맞춘 조건 변화

**Comment by 3daysJin** [comment]
스스로 본인 콜라이더 초기화해서 들고오도록 -> 완
플레이어 캐릭터 프리팹에 해당 스크립트 추가되어 있도록 반영 -> 완

**Comment by 3daysJin** [comment]
모바일 조작에 맞춘 조건 변화, 완료 
Todo : 추가 테스트 필요함

- [x] 점프는 잘되는가?
- [x] 하향 점프는 잘되는가? 
@eric1306

**Comment by eric1306** [comment]
하향점프 안됨 조이스틱 아래 연타 , 조이스틱 아래로 +점프기 누르기 다 해봤음. @3daysJin

**Comment by eric1306** [comment]
해결완료
